config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
require 'sidekiq_unique_jobs/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'client_app#index'

  ActiveAdmin.routes(self)

  constraints AdminConstraint.new do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users,
             controllers: {
               sessions: 'sessions',
               passwords: 'passwords',
             }

  get 'map', to: redirect('/', status: 302)
  get 'mobile_map', to: redirect('/new_map', status: 302)
  get 'fixed_map', to: redirect('/new_map', status: 302)

  get 's/:url_token' => 'measurement_sessions#show',
      :constraints => {
        query_string: /.+/,
      },
      :as => :short_session
  get 's/:url_token' => 'measurement_sessions#show_old' # legacy API - supports mobile apps released before 06.2019

  namespace :api do
    namespace :v2 do
      namespace :data do
        resources :sessions, only: [] do
          collection { get :last }
        end
      end
    end

    resources :measurement_sessions, path: 'sessions', only: %i[create] do
      collection do
        get :export
        get :export_by_uuid
      end
    end

    get 'averages' => 'averages#index'
    get 'averages2' => 'averages#index2'
    resources :thresholds, only: %i[show], id: /.*/
    resource :region, only: %i[show], controller: 'mobile_regions'
    resource :fixed_region, only: %i[show]
    resource :user, only: %i[show create destroy] do
      resources :sessions, only: %i[show], controller: 'user_sessions' do
        collection do
          post :sync # legacy API - supports mobile apps released before 07.2019
          post :sync_with_versioning
          post :update_session
          post :delete_session
          post :delete_session_streams
        end
      end
      get 'sessions/:uuid' => 'user_sessions#show'
      post 'settings', to: 'users#settings'
      post 'delete_account_send_code',
           to: 'confirmation_code#request_account_deletion'
      post 'delete_account_confirm',
           to: 'users#delete_account_with_confirmation_code'
    end
    resources :sensors, only: %i[index]

    namespace :realtime do
      get 'sync_measurements' => 'sessions#sync_measurements'
      resources :sessions, only: %i[create show]
      resources :measurements, only: :create
    end

    namespace :fixed do
      get 'sessions/:id/streams' => 'sessions#show_all_streams'
      get 'streams/:id' => 'streams#show'
      get 'autocomplete/tags' => 'autocomplete#tags'

      namespace :dormant do
        get 'sessions' => 'sessions#index'
      end

      namespace :active do
        get 'sessions' => 'sessions#index'
        get 'sessions2' => 'sessions#index2'
      end

      resources :threshold_alerts, only: %i[index create destroy]
      post 'destroy_alert' => 'threshold_alerts#destroy_alert'
    end

    namespace :mobile do
      get 'sessions' => 'sessions#index'
      get 'sessions/:id' => 'sessions#show'
      get 'sessions2/:id' => 'sessions#show2'
      get 'streams/:id' => 'streams#show'
      get 'autocomplete/tags' => 'autocomplete#tags'
    end

    namespace :v3 do
      resources :fixed_streams, only: %i[show]
      resources :stream_daily_averages, only: %i[index]
      get 'timelapse' => 'fixed_stream_clusters#index'
      get 'flipper_enabled/:feature_key' => 'flipper#enabled?'
    end

    get 'measurements' => 'measurements#index'

    resources :short_url, only: %i[index]

    get 'autocomplete/usernames' => 'autocomplete#usernames'
  end

  get '*path', to: 'client_app#index', via: :all
end

app/views/shared/_favicon.html.haml
/ Favicons
= favicon_link_tag "favicon.ico"
= favicon_link_tag "apple-touch-icon.png", rel: "apple-touch-icon", type: "image/png", sizes: "180x180"
= favicon_link_tag "favicon-32x32.png", rel: "icon", type: "image/png", sizes: "32x32"
= favicon_link_tag "favicon-16x16.png", rel: "icon", type: "image/png", sizes: "16x16"
%link{href: "/site.webmanifest", rel: "manifest"}
%link{color: "#00b2ef", href: "/safari-pinned-tab.svg", rel: "mask-icon"}
%meta{content: "#00b2ef", name: "msapplication-TileColor"}
%meta{content: "#ffffff", name: "theme-color"}
/ End Favicons

app/views/shared/_fb_logo.html.haml
%meta{:property => "og:image", :content => "#{request.protocol}#{request.host_with_port}#{image_path("static/air-casting-logo-fb.png")}"}

app/views/shared/_gtm.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-P2QSTCN3VQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-P2QSTCN3VQ');
</script>

app/views/shared/_login_form.html.haml
#sign-in{:style => "display: none"}
  = form_for(User.new, :url => session_path(:user), :remote => true, :format => :json, :html => { :id => 'sign-in-form' }) do |f|
    %div
      = f.label :login
      = f.text_field :login

    %br

    %div
      = f.label :password
      = f.password_field :password

    %br

    %div
      = f.check_box :remember_me, :checked => true
      = f.label :remember_me

    %br

    %div
      = f.submit "Sign in"
      = link_to 'Cancel', '#', :id => 'cancel-sign-in-link'

    %span.errors

app/views/shared/_noscript_gtm.html.erb
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T948MNX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->